name = "Aerosol"
uuid = "8510b696-cc45-4a64-84d0-47f429ca1505"
version = "0.3.0"
authors = ["EarthSciML authors and contributors"]

[deps]
BracketingNonlinearSolve = "70df07ce-3d50-431d-a3e7-ca6ddb60ac1e"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
EarthSciMLBase = "e53f1632-a13c-4728-9402-0c66d48804b0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"

[weakdeps]
EarthSciData = "a293c155-435f-439d-9c11-a083b6b47337"

[extensions]
EarthSciDataExt = "EarthSciData"

[compat]
BracketingNonlinearSolve = "1.5"
Dates = "1"
DynamicQuantities = "1.4.0"
EarthSciData = "0.14"
EarthSciMLBase = "0.24"
LinearAlgebra = "1.10"
ModelingToolkit = "10.10"
NonlinearSolve = "4.12"
OrdinaryDiffEq = "6.102.1"
OrdinaryDiffEqNonlinearSolve = "1.14.1"
OrdinaryDiffEqRosenbrock = "1.18.1"
Plots = "1.41.1"
Reexport = "1.2"
SciMLBase = "2.120.0"
SteadyStateDiffEq = "2.7.0"
SymbolicIndexingInterface = "0.3.45"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EarthSciData = "a293c155-435f-439d-9c11-a083b6b47337"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "Dates", "EarthSciData", "NonlinearSolve", "Symbolics", "TestItemRunner"]
